#!/usr/bin/bash

# This is a simple script to cd into a directory and then remove everything following a specific pattern. I use it to clear my screenshots folder generated by gnome-screenshot, hence the name, but you could use it for any simple cd & rm operation.

DIR=~/Pictures
FORM=Screenshot*

echo "Continuing will erase all files in $DIR with pattern $FORM. Are you sure? [y/n]"
read confirm
if [[ $confirm =~ ^[yY]$ ]]; then
	echo "Erasing all files in $DIR with pattern $FORM."
	cd $DIR
	rm $FORM
	echo "Done!"
else
	"Exiting."
fi
